### PR TITLE
Set version to swift 5 and check in the shared xcschemes

### PR DESCRIPTION
**Pull request by ampm**
Hi Damiaan, this PR include blowing updates, pls help to review and merge it.

-  Set the swift version as Swift 5
-  Check in the shared xcschemes
    This is required for Carthage, otherwise, it will complain `Dependency "A-Star" has no shared framework schemes`.

Thanks.

### CODE REVIEW

**Comment by Dev1an** [comment]
@ampm Thanks for fixing my project file. This looks good.
I [deleted](5d2a162f25857e1e8ad1e58ae229cb916f1a05da) my old schemes under xcuserdata and [configured](705a9ebd4bf93460b19ce8b18c03c8b1190d7059) the macOS scheme for testing.

**Comment by Dev1an** [comment]
I tagged a new release. Let me know if it works now in your Carthage workflow.

**Comment by ampm** [comment]
> I tagged a new release. Let me know if it works now in your Carthage workflow.

It works now. Thanks, Damiaan!

**Comment by ampm** [comment]
Hi @Dev1an, one more thing, do you mind to change the framework name as `AStar`?  aStar kind of not camel cased properly as a framework name.
And MappaMundi has a minimum deployment target of 10.0, this framework's is higher than it. Can we set it to 10.0 ? (I can create another PR for it.)
Thanks a lot.

**Pull request merged**
