### PR TITLE
remove self if no path

### PR DESCRIPTION
**Pull request by ampm**
Hi @Dev1an , this PR include:

- Add self at index 0 if only there is a path, otherwise, just leave the path empty(UnitTest added).
- Correct the tests target name in the `Package.swift.`

### CODE REVIEW

**Comment by Dev1an** [comment]
@ampm What is the advantage of doing this?

**Comment by ampm** [comment]
> @ampm What is the advantage of doing this?

Hi @Dev1an , take this test case, for example, we can know if there is a path between two points by checking the `path.count  > 0`, otherwise, we have to check it like this `path.count > 1`, but the only node in the path is the starting point itself.
In my opinion, the previous one is more intuitive, how do you think about it?

```
func testEmptyPath() {
    let path = c3.findPath(to: c5)
    XCTAssertEqual(path.count, 0)
}
```

**Comment by ampm** [comment]
hi @Dev1an , looking forward for your feedback. thanks

**Comment by Dev1an** [comment]
Thanks for all your contributions @ampm !

Yeah it is true that it looks nicer when the path is completely empty rather than a collection of one element. But this is again a breaking change so I will have to do a major version bump again. I don't think this is so much of a problem though because I doubt there are many people using this library.

So if you have other proposals for breaking changes please post them now, and then I can do a big major update with all of them together, rather than having to do major version bumps every day 😉.

**Comment by Dev1an** [comment]
And I don't think you need to rename the test target in Package.swift (91a686d3df668f490d8a73e7e01d0cae69473cdd). [SPM](https://swift.org/package-manager/) Reads the directory names, and not the target names from the Xcode project. You can test the Package.swift file by running `swift test` in the root directory of this project using the terminal.

When I try this on your renaming commit, I get [the following error](https://circleci.com/gh/Dev1an/A-Star/19): 
```
'AStar' /Users/damiaan/Documents/Projecten/A-Star: error: Source files for target AStarTests_macOS should be located under 'Sources/AStarTests_macOS', or a custom sources path can be set with the 'path' property in Package.swift
```

So could you remove the Package.swift change? You could also add the extra `path` property but I would prefer not to, because the tests are not macOS related and can also be run on a Linux machine. (I am already doing this actually for continuous integration, see [CircleCI](https://circleci.com/gh/Dev1an/A-Star/tree/master)).

When the tests pass, I will review and accept your proposal.

**Comment by ampm** [comment]
Hi @Dev1an, no other thoughts so far.  I'll try to collect them together if i have in the future. 
And have reverted that commit, now the test should pass.
Thanks very much.

**Comment by ampm** [comment]
hi @Dev1an,  the tests passed. can we merge this PR? thanks.

**Comment by Dev1an** [comment]
I merged your commits and added some clean up. You can try it using version [3.0.0-beta-1](https://github.com/Dev1an/A-Star/releases/tag/3.0.0-beta-1)

**Pull request closed without merging**
